### ISSUE TITLE
重试机制有问题！！！

### ISSUE THREAD

**Issue by xiaochao** [yunpian/yunpian-python-sdk#2]
你们的SDK里有重试机制，但是我遇到了一个情况，就是第一次请求超时了，这时候就会重试，发送第二次请求，但是第一次请求服务器已经处理了，只是返回超时了，于是第二次请求就报错了，实际情况如下！

**Comment by bingone** [comment]
超时重试机制设置时间为5S，如果发送有问题。请先检查下网络环境。如有问题，欢迎反馈
