### ISSUE TITLE
怎么不标明支持python的版本

### ISSUE THREAD

**Issue by jiftle** [yunpian/yunpian-python-sdk#4]
怎么不标明支持python的版本

**Comment by bingone** [comment]
已经注明目前的PythonSDK为Python2，Python3在开发中，敬请期待

**Comment by jiftle** [comment]
ok good

**Comment by dzh** [comment]
@jiftle https://github.com/yunpian/yunpian-python-sdk v1.0.0支持python3

**Comment by jiftle** [comment]
thanks
