### ISSUE TITLE
使用pip安装的版本有问题，tpl_signle_send的拼写错误没更新过来

### ISSUE THREAD

**Issue by wdjwxh** [yunpian/yunpian-python-sdk#5]
RT

**Comment by CCBTony** [comment]
python新sdk已出，支持py2/3，老sdk暂停维护
https://github.com/yunpian/sms/tree/master/yunpian/python/ypclient

**Comment by dzh** [comment]
@wdjwxh https://github.com/yunpian/yunpian-python-sdk 新版v1.0.0已发布
